name: "Upload yomi-reimu"

on:
  workflow_run:
    workflows: ["Zip Reimu"]
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AnarkisGaming/workshop@v1
        with:
          appID: 2212330
          publishedFileID: 3009963287
          path: "EXPORT/Reimu"
          changelog: ${{ github.event.head_commit.message }}              
        env:
          STEAM_ACCOUNT_NAME: ${{ secrets.accountname }}
          STEAM_PASSWORD: ${{ secrets.password }}
