name: "Zip Meiling"

on:
  push:
    paths:
      - "HongMeiling/**"

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: HongMeiling/
          dest: EXPORT/Meiling/HongMeiling.zip
          
