name: "Zip Reimu"

on:
  push:
    paths:
      - "HakureiReimu/**"

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AnarkisGaming/workshop@v1
        with:
          appID: 2212330
          publishedFileID: CHANGEME
          changelog: ${{ github.event.head_commit.message }} 
        env:
          STEAM_ACCOUNT_NAME: ${{ secrets.accountname }}
          STEAM_PASSWORD: ${{ secrets.password }}
