name: "Zip Reimu"

on:
  push:
    paths:
      - "HakureiReimu/**"

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: HongMeiling/
          dest: EXPORT/Reimu/HakureiReimu.zip
          recursive: false
          
      - name: "retroactively add latest zip reimu"
        uses: stefanzweifel/git-auto-commit-action@v4  